services:
  artvis-db:
    container_name: artvis-db
    networks:
      - artvis-network
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: on-failure
    volumes:
      - ./import.sh:/var/lib/neo4j/import.sh
      - ./certificates:/var/lib/neo4j/certificates
      - ./neo4j_dump:/var/lib/neo4j/dump
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: ${NEO4J_AUTH}
      NEO4J_PLUGINS: '["apoc", "apoc-extended", "graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: ${NEO4J_dbms_security_procedures_unrestricted}
      NEO4J_server_memory_pagecache_size: ${NEO4J_server_memory_pagecache_size}
      NEO4J_server_memory_heap_initial__size: ${NEO4J_server_memory_heap_initial__size}
      NEO4J_server_memory_heap_max__size: ${NEO4J_server_memory_heap_max__size}
      NEO4J_dbms_ssl_policy_bolt_enabled: ${NEO4J_dbms_ssl_policy_bolt_enabled}
      NEO4J_dbms_ssl_policy_bolt_base__directory: ${NEO4J_dbms_ssl_policy_bolt_base__directory}
      NEO4J_dbms_ssl_policy_bolt_private__key: ${NEO4J_dbms_ssl_policy_bolt_private__key}
      NEO4J_dbms_ssl_policy_bolt_public__certificate: ${NEO4J_dbms_ssl_policy_bolt_public__certificate}
      NEO4J_dbms_ssl_policy_bolt_client__auth: ${NEO4J_dbms_ssl_policy_bolt_client__auth}
      NEO4J_server_bolt_tls__level: ${NEO4J_server_bolt_tls__level}
      NEO4J_server_https_enabled: ${NEO4J_server_https_enabled}
      NEO4J_dbms_ssl_policy_https_enabled: ${NEO4J_dbms_ssl_policy_https_enabled}
      NEO4J_dbms_ssl_policy_https_base__directory: ${NEO4J_dbms_ssl_policy_https_base__directory}
      NEO4J_dbms_ssl_policy_https_private__key: ${NEO4J_dbms_ssl_policy_https_private__key}
      NEO4J_dbms_ssl_policy_https_public__certificate: ${NEO4J_dbms_ssl_policy_https_public__certificate}
      NEO4J_dbms_ssl_policy_https_client__auth: ${NEO4J_dbms_ssl_policy_https_client__auth}

    build:
      context: ./
      dockerfile: Dockerfile
networks:
  artvis-network:
    name: artvis-network
    driver: bridge
