dbms.directories.import=import

dbms.tx_state.memory_allocation=ON_HEAP

dbms.default_listen_address=0.0.0.0

dbms.connector.bolt.enabled=true
dbms.connector.bolt.tls_level=OPTIONAL
dbms.connector.bolt.listen_address=0.0.0.0:7687
dbms.connector.bolt.advertised_address=artvis.cvast.tuwien.ac.at

server.https.enabled=false
dbms.connector.https.listen_address=:7473
dbms.connector.https.advertised_address=artvis.cvast.tuwien.ac.at

dbms.ssl.policy.bolt.enabled=true
dbms.ssl.policy.bolt.base_directory=certificates/bolt
dbms.ssl.policy.bolt.private_key=private.key
dbms.ssl.policy.bolt.public_certificate=public.crt
dbms.ssl.policy.bolt.client_auth=NONE

dbms.ssl.policy.https.enabled=true
dbms.ssl.policy.https.base_directory=certificates/https
dbms.ssl.policy.https.private_key=private.key
dbms.ssl.policy.https.public_certificate=public.crt
dbms.ssl.policy.https.client_auth=NONE

metrics.csv.rotation.compression=zip

dbms.security.procedures.allowlist=apoc.*,gds.*

server.jvm.additional=-XX:+UseG1GC

server.jvm.additional=-XX:-OmitStackTraceInFastThrow

server.jvm.additional=-XX:+AlwaysPreTouch

server.jvm.additional=-XX:+UnlockExperimentalVMOptions
server.jvm.additional=-XX:+TrustFinalNonStaticFields

server.jvm.additional=-XX:+DisableExplicitGC

server.jvm.additional=-XX:MaxInlineLevel=15

server.jvm.additional=-XX:-UseBiasedLocking

server.jvm.additional=-Djdk.nio.maxCachedBufferSize=262144

server.jvm.additional=-Dio.netty.tryReflectionSetAccessible=true

server.jvm.additional=-Djdk.tls.ephemeralDHKeySize=2048

server.jvm.additional=-Djdk.tls.rejectClientInitiatedRenegotiation=true

server.jvm.additional=-XX:FlightRecorderOptions=stackdepth=256

server.jvm.additional=-XX:+UnlockDiagnosticVMOptions
server.jvm.additional=-XX:+DebugNonSafepoints

server.jvm.additional=-Dlog4j2.disable.jmx=true

dbms.tx_log.rotation.retention_policy=100M size

# server.memory.pagecache.size=256M

dbms.default_listen_address=0.0.0.0

causal_clustering.discovery_advertised_address=54424639a7ca:5000

causal_clustering.transaction_advertised_address=54424639a7ca:6000

causal_clustering.raft_advertised_address=54424639a7ca:7000
# server.memory.heap.max_size=2g
# server.memory.heap.initial_size=1g
dbms.directories.logs=/logs
dbms.default_database=neo4j
